checks:
  php: true

tools:
  php_mess_detector: true
  php_cpd: true
  php_loc:
    excluded_dirs: [vendor]
  php_pdepend:
    excluded_dirs: [vendor]
  external_code_coverage:
    runs: 1

build:
  environment:
    php:
      version: 7.4
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
