language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_install:
    - curl http://tarantool.org/dist/public.key | sudo apt-key add -
    - echo "deb http://tarantool.org/dist/master/ubuntu `lsb_release -c -s` main" | sudo tee -a /etc/apt/sources.list.d/tarantool.list
    - sudo apt-get update

install:
    - sudo apt-get -y install tarantool php5-tarantool luarocks

    - printf "extension = tarantool.so\n" >> ~/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/php.ini;

    - mkdir ~/.luarocks
    - echo "rocks_servers = {[[http://rocks.tarantool.org/]]}" >> ~/.luarocks/config.lua
    - luarocks install queue --local

    - composer install

before_script:
    - sudo cp ./tests/Integration/instance.lua /etc/tarantool/instances.enabled
    - sudo tarantoolctl start instance
    - >
        for i in `seq 1 10`; do
            if sudo tarantoolctl status instance; then
                break;
            fi;
            sleep 1;
        done

script:
    - >
        bash -c 'if [[ 5.6 == $TRAVIS_PHP_VERSION ]]; then
            phpunit -v --coverage-clover coverage.clover;
        else
            phpunit -v;
        fi;'

after_script:
    # code-coverage for scrutinizer-ci
    - >
        bash -c 'if [[ 5.6 == $TRAVIS_PHP_VERSION ]]; then
            wget https://scrutinizer-ci.com/ocular.phar;
            php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
        fi;'
