os: linux
language: shell
services: [docker]

env:
  global:
    TNT_IMAGE='tarantool/tarantool:2.6'
    PHP_IMAGE='php:8.0-cli'

  jobs:
    - PHP_IMAGE='php:7.1-cli'
    - PHP_IMAGE='php:7.2-cli'
    - PHP_IMAGE='php:7.3-cli' QA=1
    - PHP_IMAGE='php:7.4-cli' COVERAGE_FILE='coverage.clover'
    - PHP_IMAGE='php:8.0-cli'

    - TNT_IMAGE='tarantool/tarantool:1.7'
    - TNT_IMAGE='tarantool/tarantool:1.9'
    - TNT_IMAGE='tarantool/tarantool:1'
    - TNT_IMAGE='tarantool/tarantool:2.1'
    - TNT_IMAGE='tarantool/tarantool:2.3'
    - TNT_IMAGE='tarantool/tarantool:2.4'
    - TNT_IMAGE='tarantool/tarantool:2.5'

install:
  - ./dockerfile.sh | tee /dev/tty | docker build -t queue -

script:
  - docker network create tarantool-php
  - docker run --net=tarantool-php --rm ${TNT_IMAGE} /usr/local/bin/tarantool --version
  - docker run -d --net=tarantool-php --name=tarantool -v `pwd`:/queue -e TNT_LISTEN_URI=$TNT_LISTEN_URI ${TNT_IMAGE} tarantool /queue/tests/Integration/queues.lua
  - docker run --rm --net=tarantool-php -v `pwd`:/queue -w /queue queue
  - if [[ -n "$QA" ]]; then
      docker run --net=tarantool-php --rm -v $PWD:/queue -w /queue queue php vendor/bin/php-cs-fixer fix --dry-run --diff --verbose . &&
      docker run --net=tarantool-php --rm -v $PWD:/queue -w /queue queue php vendor/bin/psalm;
    fi

after_script:
  - if [[ -f "$COVERAGE_FILE" ]]; then
      curl -sSOL https://scrutinizer-ci.com/ocular.phar &&
      docker run --rm -v $(pwd):/queue -w /queue queue php ocular.phar code-coverage:upload --format=php-clover "$COVERAGE_FILE";
    fi
