sudo: required

language: bash

services:
  - docker

env:
  global:
    TNT_IMAGE='tarantool/tarantool:2'

  matrix:
    - PHP_IMAGE='php:7.1-cli' TNT_CLIENT=pecl PHPUNIT_OPTS='--coverage-clover=coverage.clover'
    - PHP_IMAGE='php:7.1-cli' CHECK_CS=1
    - PHP_IMAGE='php:7.2-cli' PHPUNIT_OPTS='--coverage-clover=coverage.clover'
    - PHP_IMAGE='php:7.3-cli'

    - PHP_IMAGE='php:7.3-cli' TNT_IMAGE='tarantool/tarantool:1.7'
    - PHP_IMAGE='php:7.3-cli' TNT_IMAGE='tarantool/tarantool:1.9'
    - PHP_IMAGE='php:7.3-cli' TNT_IMAGE='tarantool/tarantool:1'
    - PHP_IMAGE='php:7.3-cli' TNT_IMAGE='tarantool/tarantool:2.1'

install:
  - ./dockerfile.sh | tee /dev/tty | docker build -t queue -

script:
  - docker network create tarantool-php
  - docker run --net=tarantool-php --rm ${TNT_IMAGE} /usr/local/bin/tarantool --version
  - docker run -d --net=tarantool-php --name=tarantool -v `pwd`:/queue ${TNT_IMAGE} tarantool /queue/tests/Integration/queues.lua
  - docker run --rm --net=tarantool-php -v `pwd`:/queue -w /queue -e PHPUNIT_OPTS="$PHPUNIT_OPTS" queue

after_script:
  - if [[ -f coverage.clover ]]; then
      curl -sSOL https://scrutinizer-ci.com/ocular.phar &&
      docker run --rm -v $(pwd):/queue -w /queue queue php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
    fi
